### ISSUE TITLE
Icons not visible in PDF when using the `vitepress-export-pdf` plugin

### ISSUE THREAD

**Issue by Teraskull** [yuyinws/vitepress-plugin-group-icons#18]
When printing the documentation to PDF with [`vitepress-export-pdf`](https://github.com/condorheroblog/vitepress-export-pdf), the icons are not loaded on the page.

This is the code responsible for loading the virtual icons:

https://github.com/yuyinws/vitepress-plugin-group-icons/blob/6cb03da033b3c2b4d346437ff9441d5a06e06bb5/src/vite.ts#L47-L55

I was able to monkeypatch the `dist/index.mjs` like this:

```js
async load(id) {
	if (id === resolvedVirtualCssId) {
		const safeMatches = matches.size > 0 ? matches : new Set(Object.keys(builtinIcons));
		const { css } = await generateCSS(safeMatches, options);
		oldMatches = new Set(matches);
		return css;
	}

	return undefined;
},
```

And now the plugin loads the icons properly.

Would be nice if it's possible to support this directly.

Thanks!

**Comment by yuyinws** [comment]
The cause of this problem is the css attribute `background` was ignored in 
browser print mode. You can add this code to overwrite it:

```css
@media print {
  * {
    -webkit-print-color-adjust: exact !important;
    color-adjust: exact !important;
    print-color-adjust: exact !important;
  }
}

```
